### ISSUE TITLE
track upstream sources

### ISSUE THREAD

**Issue by schmir** [trustlines-network/contract-library#4]
We should document which external source code we imported into our repository. 
Ideally this would include where it came from, which exact version has been imported and where new versions can be found. probably also what the license is.

This will make it easier to merge changes from upstream back.

**Comment by schmir** [comment]
@weilbith, @cducrest can you please fill in the information?

**Comment by cducrest** [comment]
I have imported the `Ownlable.sol` and `it_set_lib.sol` contracts from the contracts repository to the blockchain repository. As such, they are not external sources to me and there is no information such as version, or license I can add.
I can attempt to backtrack the information for every contract if relevant though.

**Comment by cducrest** [comment]
I added the sources I could track to the README.md file, if we deem it sufficient then this issue can be closed.

**Comment by weilbith** [comment]
Since I was a bit late for PR #5, I confirm the changes by @cducrest this way. Looks exactly how I would have done it. :+1:

**Comment by berndbohmeier** [comment]
I added the origin of Destructable but SafeMath is still unknown. It was added by Alex, so I dont know it.

**Comment by berndbohmeier** [comment]
@schmir is that enough so far to close this?

**Comment by schmir** [comment]
Let's hope so. We will notice, when we try to integrate changes from upstream.
